### ISSUE TITLE
感到很纳闷，一个纵向的TextView，加一些单指移动，双指缩放干嘛，核心功能却基本没实现

### ISSUE THREAD

**Issue by hackware1993** [jinguangyue/AddwordDemo#2]

**Comment by jinguangyue** [comment]
你觉得核心功能是什么

**Comment by hackware1993** [comment]
![textview](https://cloud.githubusercontent.com/assets/6748135/16981965/de0b3006-4e9f-11e6-9c6b-0bdaf099d882.png)
额，试想一下这样的布局，用你这个很难实现

**Comment by jinguangyue** [comment]
我遇到的需求是图片加字， 对字进行竖排显示， 要求可移动缩放， 你的这个效果我写的这个是可以实现的， 行间距 字大小都能调， 这里我的主要难点就是Textview的横竖排切换，竖排的时候字的方向不能变， 我提供了一种解决方案是每一个字都是一个Textview， 目前满足了我的所有需求， 我还没想到更好的方法实现， 你能提供给我一种方便强大的思路是极好的对我来说

**Comment by hackware1993** [comment]
基本上找遍了所有的资源，就你这个稍微好些，但还是满足不了需求，我打算自己measure、draw了，不过很麻烦，需考虑对齐方式，数字及单词等不可拆分字符的处理。

**Comment by hackware1993** [comment]
每个字一个TextView我接受不了，还是draw合理些

**Comment by jinguangyue** [comment]
那你试试吧 目前我用的方案占用内存还可以接受， 我弄了满屏的文字会占用5M以下的内存，你是要做什么样的需求

**Comment by luo15140128** [comment]
如何保存？ 我保存的时候
android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
AddWordFrame.onDraw 这位置老报错
