### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: length=12; index=-1

### ISSUE THREAD

**Issue by andyxialm** [jinguangyue/AddwordDemo#3]
![image](https://cloud.githubusercontent.com/assets/5976556/19434561/c427bcb0-9498-11e6-85c1-846229326e6d.png)

另外存在几个问题。
1. 好像无法换行？
2. 建议使用drawText，addView这种不太合理

**Comment by jinguangyue** [comment]
你是用我的例子试的么 
因为我还有其他的需求 所以要用addview的方式

**Comment by jinguangyue** [comment]
你可以下载apk看看有没有问题

**Comment by andyxialm** [comment]
@jinguangyue 是用你的demo apk 运行的
