### ISSUE TITLE
输入字体数量到10个左右就不能自适应了

### ISSUE THREAD

**Issue by fangxiong** [jinguangyue/AddwordDemo#7]

**Comment by jinguangyue** [comment]
能发个截图么

**Comment by fangxiong** [comment]
![image](https://user-images.githubusercontent.com/26686093/48613308-55f95480-e9c6-11e8-9712-e6df754103d9.png)

**Comment by fangxiong** [comment]
我手机大概输入九个字再输入后续就无法显示了 你可以在你的demo里试试

**Comment by jinguangyue** [comment]
应该是行放不下了 你可以改代码把它放开 或者自动转到第二行

**Comment by fangxiong** [comment]
我看了会你的代码 目前没找到问题所在 能给点指示吗

**Comment by jinguangyue** [comment]
添加文字代码在自定义的TextView里 每一个横行是一个自定义的Linearlayout 主要看看这俩个类

**Comment by jinguangyue** [comment]
缩放用的是 matrix   文字添加的时候每一个字是一个textView 因为这样才能完美横竖切换

**Comment by fangxiong** [comment]
AddWordInsideLinearlayout  AddWordOutsideLinearLayout两个类我也看了 确实没找到问题所在 字体编辑框在竖的状态下没问题在横着的状态下有问题

**Comment by jinguangyue** [comment]
那应该是外层判断了 最大就显示那些 看看他们的外层控件是否有限制 不过我觉得这时候你可以点击回车换行显示了

**Comment by fangxiong** [comment]
我再研究研究 这是一个bug 不能因为这样就去换行显示呀 不符合需求...  麻烦作者解决后通知下

**Comment by fangxiong** [comment]
这种addView()方式 字体编辑框字数就固定死了 如果设置字的大小为30px 我手机只显示9个字 即使缩小view  
也只显示9个字 所以我采用办法设置初始字体特别小 比如设置为5 理应就能一行显示四五十个字了 然后代码设置将其放大 就能实现需求了

**Comment by fangxiong** [comment]
感谢作者的无私奉献

**Comment by jinguangyue** [comment]
6666666
