### ISSUE TITLE
webview 就不能缩放了

### ISSUE THREAD

**Issue by TigerChain** [jinguangyue/AddwordDemo#8]
如果是 webview 呢？双击移动到手指位置放大两倍，然后双击再缩小，并且支持双指放大。

**Comment by jinguangyue** [comment]
还有缩放 webview 需求？

**Comment by TigerChain** [comment]
> 还有缩放 webview 需求？

是呀，

**Comment by jinguangyue** [comment]
Webview 自己支持自己缩放呀 你还要拖动？ 自求多福啦兄dei

**Comment by TigerChain** [comment]
> Webview 自己支持自己缩放呀 你还要拖动？ 自求多福啦兄dei

自己支持的满足不了，我重写手势了
